-- 1

SELECT NOME, ANO FROM FILMES

-- 2

SELECT NOME, ANO, DURACAO FROM FILMES ORDER BY ANO ASC

-- 3

SELECT NOME, ANO, DURACAO FROM FILMES WHERE NOME = 'DE VOLTA PARA O FUTURO'

-- 4 

SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO = 1997

-- 5

SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO > 2000

-- 6

SELECT NOME, ANO, DURACAO FROM FILMES WHERE DURACAO > 100 AND DURACAO < 150 ORDER BY DURACAO

-- 7

SELECT ANO, COUNT(ANO) QUANTIDADE FROM FILMES GROUP BY ANO ORDER BY QUANTIDADE DESC

-- 8

SELECT * FROM ATORES WHERE GENERO = 'M'

-- 9 

SELECT * FROM ATORES WHERE GENERO = 'F' ORDER BY PRIMEIRONOME

-- 10

SELECT F.NOME, G.GENERO FROM FILMESGENERO FG
INNER JOIN FILMES F ON 	FG.IDFILME = F.ID
INNER JOIN GENEROS G ON FG.IDGENERO = G.ID

-- 11

SELECT F.NOME, G.GENERO FROM FILMESGENERO FG
INNER JOIN FILMES F ON FG.IDFILME = F.ID
INNER JOIN GENEROS G ON FG.IDGENERO = G.ID
WHERE G.GENERO = 'MISTÉRIO'

-- 12

SELECT F.NOME, A.PRIMEIRONOME, A.ULTIMONOME, E.PAPEL FROM FILMES F
INNER JOIN ELENCOFILME E ON F.ID = E.IDFILME
INNER JOIN ATORES A ON A.ID = E.IDATOR




